name: merchant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  fl_chart: ^0.66.0
  excel: ^2.1.0
  open_file: ^3.3.2
  shared_preferences: ^2.2.2
  path_provider: ^2.0.15
  # Add HTTP dependency for API calls
  http: ^1.1.0

  # Add Provider dependency for state management (if you prefer state management)
  provider: ^6.0.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/config.json
    - assets/images/
    - assets/fonts/

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/poppins_regular.ttf
            weight: 400
          - asset: assets/fonts/poppins_bold.ttf
            weight: 700
          - asset: assets/fonts/poppins_med.ttf
            weight: 500
          - asset: assets/fonts/poppins_sb.ttf
            weight: 600




flutter_launcher_icons:
    android: true
    ios: false # Disable iOS
    image_path: "assets/images/logo.jpg"
